//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.lessons = new HashSet<Lesson>();
            this.students = new HashSet<Student>();
            this.groups = new HashSet<Group>();
        }
    
        public int GradeID { get; set; }
        public string Section { get; set; }
        public byte GradeNo { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Lesson> lessons { get; set; }
        public virtual ICollection<Student> students { get; set; }
        public virtual ICollection<Group> groups { get; set; }
    }
}
