//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson_student
    {
        public int LessonID { get; set; }
        public int StudentID { get; set; }
        public bool IsPresent { get; set; }
        public Nullable<int> MarkID { get; set; }
    
        public virtual Lesson lesson { get; set; }
        public virtual Student student { get; set; }
        public virtual Mark marks { get; set; }
    }
}
