//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public Mark()
        {
            this.lesson_student = new HashSet<lesson_student>();
        }
    
        public int MarkID { get; set; }
        public decimal Value { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<lesson_student> lesson_student { get; set; }
    }
}
