//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.students = new HashSet<Student>();
        }
    
        public string Job { get; set; }
        public int ParentID { get; set; }
    
        public virtual User user { get; set; }
        public virtual ICollection<Student> students { get; set; }
    }
}
