//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.parents = new HashSet<Parent>();
            this.groups = new HashSet<Group>();
            this.lesson_student = new HashSet<lesson_student>();
        }
    
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public int StudentID { get; set; }
        public int GradeID { get; set; }
    
        public virtual Grade grade { get; set; }
        public virtual User user { get; set; }
        public virtual ICollection<Parent> parents { get; set; }
        public virtual ICollection<Group> groups { get; set; }
        public virtual ICollection<lesson_student> lesson_student { get; set; }
    }
}
