//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentsList
    {
        public int Student_ID { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string patronymic { get; set; }
        public string Grade { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> Date_of_join { get; set; }
    }
}
