//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJournalEFDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.lessons = new HashSet<Lesson>();
            this.groups = new HashSet<Group>();
        }
    
        public int SubjectID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Lesson> lessons { get; set; }
        public virtual ICollection<Group> groups { get; set; }
    }
}
